name: test-payments

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      STRIPE_SECRET_FROM_ENV_FILE: ${{ secrets.STRIPE_SECRET_FROM_ENV_FILE }}
    steps:
      - uses: actions/checkout@v2
      - run: cd payments && npm i && npm run test:ci
